import WifiIcon from '@mui/icons-material/Wifi';
import WbIncandescentOutlinedIcon from '@mui/icons-material/WbIncandescentOutlined';
import PowerOutlinedIcon from '@mui/icons-material/PowerOutlined';
import LiquorOutlinedIcon from '@mui/icons-material/LiquorOutlined';
import { OverridableComponent } from '@mui/material/OverridableComponent';
import { SvgIconTypeMap } from '@mui/material/SvgIcon/SvgIcon';

export const iconMap: {
  [key: string]: OverridableComponent<SvgIconTypeMap<{}, 'svg'>> & {
    muiName: string;
  };
} = {
  WiFi: WifiIcon,
  'Reading Light': WbIncandescentOutlinedIcon,
  'Charging Point': PowerOutlinedIcon,
  'Water Bottle': LiquorOutlinedIcon,
};

export const amenities = [
  'Wifi',
  'Reading light',
  'Charging Point',
  'Water Bottle',
  'Wifi',
  'Reading light',
];

export const searchResults = [
  {
    vehicleClassType: 'SLEEPER',
    vehicleType: 'AC',
    vehicleNumber: '4500',
    station: [
      {
        sourceName: 'mumbai',
        destinationName: 'mumbai',
        stationId: 3,
        sourceDepartureTime: ['13:30'],
        sourceArrivalTime: ['13:15'],
        sourceDuration: 4.5,
        sourceDistance: 160,
        BoardingPoint: [{ time: '15:10', locationName: 'andheri' }],
        destinationDepartureTime: ['15:00'],
        destinationArrivalTime: ['14:45'],
        destinationDistance: 0,
        destinationDuration: 0,
      },
      {
        sourceName: 'panvel',
        destinationName: 'panvel',
        stationId: 2,
        sourceDepartureTime: ['12:30'],
        sourceArrivalTime: ['12:15'],
        sourceDuration: 3.5,
        sourceDistance: 120,
        BoardingPoint: [{ time: '16:10', locationName: 'inner panvel' }],
        destinationDepartureTime: ['16:00'],
        destinationArrivalTime: ['15:45'],
        destinationDistance: 40,
        destinationDuration: 1,
      },
    ],
    TotalAvailableSeat: '16',
    seatDetails: [
      {
        seatNo: 'L1',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L2',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L3',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L4',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L5',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L6',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L7',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L8',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'L9',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U10',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U11',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U12',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U13',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U14',
        seatFare: 340,
        status: 'unavailable',
        bookedGender: 'male',
      },
      {
        seatNo: 'U15',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U16',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        seatNo: 'U17',
        seatFare: 340,
        status: 'unavailable',
        bookedGender: 'female',
      },
      {
        seatNo: 'U18',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
    ],
    vehicleName: 'meghdoot',
    dayOnWhichItRuns: [
      {
        day1: 'monday',
        day2: 'tuesday',
        day3: 'wednessday',
        day4: 'thrusday',
        day5: 'friday',
        day6: 'saturday',
        day7: 'sunday',
      },
    ],
    operatorName: 'MSRTC',
    amenities: ['WiFi', 'Reading Light', 'Charging Point', 'Water Bottle'],
    totalDistance: 40,
    totalTravelTime: 2,
    fixedFare: 480,
  },
  {
    vehicleClassType: 'SEATER',
    vehicleType: 'NONAC',
    vehicleNumber: '5000',
    station: [
      {
        sourceName: 'mumbai',
        destinationName: 'mumbai',
        stationId: 3,
        sourceDepartureTime: ['13:30'],
        sourceArrivalTime: ['13:15'],
        sourceDuration: 4.5,
        sourceDistance: 160,
        BoardingPoint: [{ time: '15:10', locationName: 'andheri' }],
        destinationDepartureTime: ['15:00'],
        destinationArrivalTime: ['14:45'],
        destinationDistance: 0,
        destinationDuration: 0,
      },
      {
        sourceName: 'panvel',
        destinationName: 'panvel',
        stationId: 2,
        sourceDepartureTime: ['12:30'],
        sourceArrivalTime: ['12:15'],
        sourceDuration: 3.5,
        sourceDistance: 120,
        BoardingPoint: [{ time: '16:10', locationName: 'inner panvel' }],
        destinationDepartureTime: ['16:00'],
        destinationArrivalTime: ['15:45'],
        destinationDistance: 40,
        destinationDuration: 1,
      },
    ],
    TotalAvailableSeat: '16',
    seatDetails: [
      {
        deck: 'lower Deck',
        seatNo: 'L1',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L2',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L3',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L4',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L5',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L6',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L7',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L8',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U9',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U10',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U11',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U12',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U13',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U14',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U15',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U16',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
    ],
    vehicleName: 'meghdoot',
    dayOnWhichItRuns: [
      {
        day1: 'monday',
        day2: 'tuesday',
        day3: 'wednessday',
        day4: 'thrusday',
        day5: 'friday',
        day6: 'saturday',
        day7: 'sunday',
      },
    ],
    operatorName: 'MSRTC',
    amenities: ['WiFi', 'Reading Light', 'Charging Point', 'Water Bottle'],
    totalDistance: 40,
    totalTravelTime: 1,
    fixedFare: 240,
  },
  {
    vehicleClassType: 'SEATER',
    vehicleType: 'AC',
    vehicleNumber: '6000',
    station: [
      {
        sourceName: 'mumbai',
        destinationName: 'mumbai',
        stationId: 3,
        sourceDepartureTime: ['13:30'],
        sourceArrivalTime: ['13:15'],
        sourceDuration: 4.5,
        sourceDistance: 160,
        BoardingPoint: [{ time: '15:10', locationName: 'andheri' }],
        destinationDepartureTime: ['15:00'],
        destinationArrivalTime: ['14:45'],
        destinationDistance: 0,
        destinationDuration: 0,
      },
      {
        sourceName: 'panvel',
        destinationName: 'panvel',
        stationId: 2,
        sourceDepartureTime: ['12:30'],
        sourceArrivalTime: ['12:15'],
        sourceDuration: 3.5,
        sourceDistance: 120,
        BoardingPoint: [{ time: '16:10', locationName: 'inner panvel' }],
        destinationDepartureTime: ['16:00'],
        destinationArrivalTime: ['15:45'],
        destinationDistance: 40,
        destinationDuration: 1,
      },
    ],
    TotalAvailableSeat: '16',
    seatDetails: [
      {
        deck: 'lower Deck',
        seatNo: 'L1',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L2',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L3',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L4',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L5',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L6',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L7',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'lower Deck',
        seatNo: 'L8',
        seatFare: 440,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U9',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U10',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U11',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U12',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U13',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U14',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U15',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
      {
        deck: 'upper Deck',
        seatNo: 'U16',
        seatFare: 340,
        status: 'available',
        bookedGender: 'male',
      },
    ],
    vehicleName: 'meghdoot',
    dayOnWhichItRuns: [
      {
        day1: 'monday',
        day2: 'tuesday',
        day3: 'wednessday',
        day4: 'thrusday',
        day5: 'friday',
        day6: 'saturday',
        day7: 'sunday',
      },
    ],
    operatorName: 'MSRTC',
    amenities: ['WiFi', 'Reading Light', 'Charging Point', 'Water Bottle'],
    totalDistance: 40,
    totalTravelTime: 1,
    fixedFare: 360,
  },
];
